### PR TITLE
Fix illegal invocation errors

### LINKED ISSUE #46: TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
```
export const sendSuggestion = ((data: any): Promise<any> => {
  console.log(JSON.stringify(data));
const apiUrl = `/api/suggest/`;
return fetch(apiUrl, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(data)
}).then(checkStatus)
    .then(r => r.json())
    .then(data => {
        console.log(data);
    });
});

const checkStatus = ((response: any) => {
  if (response.ok) {
    return response;
  } else {
    var error = new Error(response.statusText);
    console.log(error);
  //return Promise.reject(error);
  }
})

```
The script crashed with error 
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
After webkack it is looks: 
```

exports.sendSuggestion = function (data) {
    var apiUrl = "/api/suggest/";
    return unfetch_1.default(apiUrl, {             //Code crashed here
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    }).then(checkStatus).then(function (r) {
        return r.json();
    }).then(function (data) {
        console.log(data);
    });
};
var checkStatus = function checkStatus(response) {
    if (response.ok) {
        return response;
    } else {
        var error = new Error(response.statusText);
        console.log(error);
    }
};
```

### PR DESCRIPTION
**Pull request by jhnns**
Fixes #46 

I can also confirm the fix in my local setup.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-export default typeof fetch=='function' ? fetch : function(url, options) {
+export default typeof fetch == 'function' && typeof window != 'undefined' ? fetch.bind(window) : function(url, options) {
```
Comment (developit) [inline src/index.js]: Seems to work if you just do `typeof fetch=='function' ? fetch.bind() :` - thoughts?

Comment (jhnns) [inline src/index.js]: Haha nice one! 👍

**Comment by balloob** [comment]
This doesn't fix it for me. Changing it to `fetch.bind(window)` does work.

@developit would you be open for a PR that changes it to explicitly bind it to `window`?

**Comment by balloob** [comment]
Never mind. It is possible to fix it in the Webpack config without updating `unfetch`. Add this to your Webpack config:

```
{
  …,
  module: {
    strictThisContextOnImports: true,
  },
  …
}
```

**Comment by developit** [comment]
How are you testing that it didn't work @balloob?

**Comment by balloob** [comment]
Sorry, it's in a private repo at work so don't have a minimal work around. Was using Webpack 3.1 and Unfetch 3.0. When I changed `bind()` to `bind(window)` I would not get the invocation error.

Can take a stab on Monday to get a minimal repro.

**Comment by developit** [comment]
That would be good - I was testing in Safari and `.bind()` was working.   Perhaps it's not in another browser?

**Comment by balloob** [comment]
I was testing it in Chrome.

**Comment by aga5tya** [comment]
@developit @balloob  I'm using isomorphic-unfetch, confirming that i still get this error on chrome.

**Comment by developit** [comment]
Hmm - can you try this in your console and tell me if it fails?

```js
let unfetch = fetch.bind();
unfetch('/').then(console.log)
```

Works for me in Chrome 59+

**Comment by aga5tya** [comment]
@developit No errors when i run the snippet in chrome console. As @balloob was mentioning, issue happens within the app only when i bundle with webpack 3.1 and run the app on chrome. Fyi I'm on chrome 60 beta version.

**Comment by developit** [comment]
One thing I just thought of - Function.prototype.bind is IE9+
